### ISSUE TITLE
Wrong Type Deduction for BNOT

### ISSUE THREAD

**Issue by XmiliaH** [dibyendumajumdar/ravi#209]
In the case where BNOT receives a float as input, it will deduce that the output is a float too. However, this is wrong since at runtime BNOT will cast the float to an integer first and return an integer. 
The problem seems to be in the parser near
https://github.com/dibyendumajumdar/ravi/blob/56a59a1f3117a8bc88206305b94398678de1bdff/src/lcode.c#L1580

To demonstrate the issue the following code will fail with ``src/lvm.c:2422: luaV_execute: Assertion `((((rb))->tt_) == (((3) | ((0) << 4))))' failed.``
```lua
local function f(x)
    local x:number = 1.0
    return (~x) + 1
end
print(f())
```
The bytecode from function f is
```
1       [10]    LOADK           1 -1    ; 1.0
2       [11]    ADDFI           2 1 -2  ; - 1
3       [11]    BNOT            2 2
4       [11]    ADDFI           2 2 -2  ; - 1
5       [11]    RETURN          2 2
6       [12]    RETURN          0 1
```
with the unexpected `ADDFI`.

**Comment by dibyendumajumdar** [comment]
Thank you for the report. I will check

**Comment by dibyendumajumdar** [comment]
The problem seems to be that BNOT will convert floats that have no decimal to int, so ADDFI fails because it was expecting a float.

**Comment by dibyendumajumdar** [comment]
I have a fix but I need to test it

**Comment by dibyendumajumdar** [comment]
I have pushed some fixes for this and the others you reported. Please check and let me know if the issues reported are now fixed

**Comment by XmiliaH** [comment]
The LEN one ist not fully fixed. I noticed that it didn't fail the way I intended since the array indexing was put in parenthesis. So the following will fail with the given description:
```lua
debug.setmetatable(1, {
    __len = function()
        return "123"
    end
})

local function f(x:integer[])
    return #x[1] + 1
end

print(f(table.intarray(2)))
```
The others looked good to me, but I noticed that in ravi_resize_array the `t->size + 10` could overflow.

**Comment by dibyendumajumdar** [comment]
Okay looks like you found a different bug here - the expression #x results in int but then int[1] is not correctly being handled

**Comment by XmiliaH** [comment]
The problem here is that https://github.com/dibyendumajumdar/ravi/blob/fe7c76fff50c098f38470757acaed3cafdf47ff1/src/lcode.c#L1270 can change the result of `e->ravi_type`. You need to swap this and the first line of the function.

**Comment by dibyendumajumdar** [comment]
I think you are correct. Thank you!
